### ISSUE TITLE
[bug] yarn cache 기록 버리기 후 오류 발생

### ISSUE THREAD

**Issue by L2HYUNN** [depromeet/pingpong-client#23]
## 이슈 내용

- #17 
- postcss를 다시 적용하기 위해서 yarn remove하면서 변한 cache기록 310개 정도를 다음과 같은 명령어를 통해 버리기 하였습니다.
```
git reset
git checkout .
git clean -fdx
```
- 그런데 이후에 prettier 적용이 안되고 eslint에서 import/no-unresolved 오류가 나오는 문제가 발생하였습니다..
- 깃허브에서 새로 git clone을 진행한 repo에서도 동일한 문제가 발생하는데 어떻게 접근해야할지 고민중에 있습니다.
- 해결을 시도하면 이것저것 repo 설정이나 lint룰을 수정하게 될 거 같아서.. 어떻게 해야할지 의견 부탁드립니다..!

@doyoonear @hwangyena

## Screenshot
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/79739512/201907376-d26355af-1879-4f40-adf6-00daa8f53cea.png">

**Comment by L2HYUNN** [comment]
현재 혼자 해결중에 있습니다..! 해결중에 기존의 yarn.lock이 yarn classic version의 파일인 거 같아 yarn install을 따로 진행해야할 거 같습니다!

현재 레포 yarn lock 파일
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79739512/201926715-90912dee-b781-4989-be18-1c09d571d456.png">

다른 팀 yarn lock 파일 ( yarn berry ) 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79739512/201926857-2bb1922b-b51e-48f5-bd83-35835a9fe840.png">

**Comment by hwangyena** [comment]
prettier부분은 저와 동일한 문제인 것 같습니다 ㅜㅜ 
정말 해결이 불가능하다면, yarn classic을 사용하거나.. npm을 써야할 것 같네요 ㅠㅠ

**Comment by L2HYUNN** [comment]
yarn berry -> yarn classic (migration)
- #27
