### ISSUE TITLE
[issue] CI issue

### ISSUE THREAD

**Issue by hwangyena** [depromeet/pingpong-client#29]
## 이슈 내용
- lint 에러가 난것도 머지가 되어있는데, CI를 그대로 통과한 것 같습니다. lint 에러 & 빌드 에러시에 merge가 불가능하도록 설정 되어있는지 확인 부탁드려요
- 또한, 다른 PR 머지 후에 남아있는 PR 이 있다면 충돌검사를 다시 해줘야하는데, 그 부분이 이루어지고 있지 않습니다. 이것도 확인 한번만 해주세요!
- 추가적으로 local 환경에서 dev에 실수로 push 하려고할때, 막는것도 넣어야할 것 같습니다.

## Screenshot
![image](https://user-images.githubusercontent.com/70925962/202468928-45cede5f-94e3-419b-93f9-97fc06baffa4.png)

**Comment by L2HYUNN** [comment]
1.lint 에러가 난것도 머지가 되어있는데, CI를 그대로 통과한 것 같습니다. lint 에러 & 빌드 에러시에 merge가 불가능하도록 설정 되어있는지 확인 부탁드려요
- 제가 lint 설정 이후에 따로 실행해보지 않아서 다음과 같은 오류가 있는지 몰랐네요. CI에 next test 관련 flow가 없어서 추가해야할 거 같습니다. 해당 Issue에 연결해서 CI 설정 작업 진행하겠습니다 :)
- ❗️현재 저번 commit 기준으로 next lint 실행해봤을때 아래와 같은 lint 문제가 있는 것을 확인했습니다. CI 추가하면서 수정 작업도 같이 진행하겠습니다~!
- CI도 설정하지만 yarn classic으로 변경되었으니 lint staged 정도는 연결하면 좋을 거 같습니다!
![image](https://user-images.githubusercontent.com/79739512/202472814-ab9d230b-ccdb-422f-ad1b-31aee28fdcf4.png)

2. 또한, 다른 PR 머지 후에 남아있는 PR 이 있다면 충돌검사를 다시 해줘야하는데, 그 부분이 이루어지고 있지 않습니다. 이것도 확인 한번만 해주세요!
- conflict 검사를 말씀하시는걸까요? (이부분은 잘 모르겠어서 도윤님께 부탁을.. @doyoonear)

3. 추가적으로 local 환경에서 dev에 실수로 push 하려고할때, 막는것도 넣어야할 것 같습니다.
- 해당 설정 같은 경우 branch protection으로 설정되어있는거로 알고 있는데 현재 dev에 push가 가능한 상태 일까요?
![image](https://user-images.githubusercontent.com/79739512/202477613-5e799b93-ad57-4144-9bb9-c96b7bf61900.png)

**Comment by hwangyena** [comment]
@L2HYUNN 3번 부분은 제가 방금 세팅했습니다! 이제 push는 안될거예요
또 3번 세팅을하면서 2번 세팅도 해결된 것으로 보이는데, 이 부분은 추후 PR 테스트로 진행해봐야 알 것 같습니다~!
확인감사합니다!
