### ISSUE TITLE
[issue] Can't resolve 'axios'

### ISSUE THREAD

**Issue by L2HYUNN** [depromeet/pingpong-client#30]
## 이슈 내용
merge과정에서 package.json에 axios 패키지가 빠진 거 같습니다.

## Screenshot
![image](https://user-images.githubusercontent.com/79739512/202493300-8b8cc345-50ad-409a-adec-f1945dc4b0cf.png)

## 기타
로컬에서 ```yarn add axios```로 해결하였습니다.

**Comment by hwangyena** [comment]
axios 추가했습니다!
