### ISSUE TITLE
[bug] tailwind에서 scrollbar가 숨겨지지 않는 이슈

### ISSUE THREAD

**Issue by L2HYUNN** [depromeet/pingpong-client#64]
## 이슈 내용
반응형을 고려한 style 작업중 scrollbar를 없애주기 위해서 아래와 같은 방법들을 적용하였으나 실패하였습니다.

<img width="400" height="450" alt="image" src="https://user-images.githubusercontent.com/79739512/204442891-5ade2842-255a-4703-b269-a333a2bd331a.png">

## 적용했던 방법

1. `tailwind-scroll-bar`설치 및 사용
- [tailwind-scroll-bar Github](https://github.com/reslear/tailwind-scrollbar-hide)
- [How to hide the scrollbar with Tailwind CSS](https://redpixelthemes.com/blog/tailwindcss-hide-scrollbar/)
- [[이슈] : Tailwind CSS 사용 시 스크롤바 숨기기](https://merrily-code.tistory.com/169)

2. `tailwind layer` 사용 
- [How to hide scrollbar on your element in Tailwind](https://dev.to/derick1530/how-to-create-scrollable-element-in-tailwind-without-a-scrollbar-4mbd)

**Comment by hwangyena** [comment]
스크롤바가 없어져야하는 요구사항이 있었나요?

**Comment by L2HYUNN** [comment]
@hwangyena 생각해보니 요구사항을 따로 확인해보지 않았었네요..! 먼저 확인해보겠습니다!

**Comment by L2HYUNN** [comment]
게시글 목록 페이지 제외 스크롤바 제거 예정
