### ISSUE TITLE
[bug] recoil duplicated atom key warning 나오는 이슈

### ISSUE THREAD

**Issue by doyoonear** [depromeet/pingpong-client#68]
## 이슈 내용
- HMR 모드에서 duplicated atom key warning 나오는 이슈

0.7.6 버전에서 해결된 이슈여서 버전업하면 해결됩니다
https://github.com/facebookexperimental/Recoil/releases/tag/0.7.6

## Screenshot
<img width="505" alt="Screen Shot 2022-12-05 at 1 23 54 AM" src="https://user-images.githubusercontent.com/46391618/205502809-905a0052-c8ed-402e-a5fc-2b2ea1425a09.png">

**Comment by doyoonear** [comment]
.env 에 `RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=false` 까지 넣어주셔야 해당 에러 콘솔에 나오지 않게됩니다! 참고부탁드려요 
@L2HYUNN @hwangyena

**Comment by L2HYUNN** [comment]
확인했습니다!
